name: Auto-update NBA Data

on:
  schedule:
    # runs daily at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:     # allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt nba_api git-lfs
          git lfs install

      - name: Run fetch script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/fetch_nba_data.py
